---
- name: Upgrade VLC Media Player to the latest version on Windows hosts
  hosts: winsys
  gather_facts: no
  tasks:
    - name: Get the latest VLC download URL
      win_shell: |
        $url = "https://www.videolan.org/vlc/download-windows.html"
        $response = Invoke-WebRequest -Uri $url -UseBasicParsing
        $downloadLink = ($response.Links | Where-Object { $_.outerHTML -match "Download VLC" }).href
        echo $downloadLink
      register: vlc_download_url

    - name: Display the download URL
      debug:
        var: vlc_download_url.stdout

    - name: Download the latest VLC installer
      win_get_url:
        url: "{{ vlc_download_url.stdout }}"
        dest: C:\Temp\vlc_installer.exe
      when: vlc_download_url.stdout != ""

    - name: Upgrade VLC Media Player
      win_package:
        path: C:\Temp\vlc_installer.exe
        arguments: /S
        state: present
      when: vlc_download_url.stdout != ""

    - name: Clean up the installer
      win_file:
        path: C:\Temp\vlc_installer.exe
        state: absent
      when: vlc_download_url.stdout != ""
